# Generated by Django 4.0.1 on 2022-01-30 13:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('short_body', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('thumb_img', models.ImageField(blank=True, default='nophoto.jpg', upload_to='destination/')),
                ('tip', multiselectfield.db.fields.MultiSelectField(choices=[('Gde jesti?', 'Gde jesti?'), ('Gde spavati?', 'Gde spavati?'), ('Sta videti?', 'Sta videti?')], max_length=35)),
                ('sort_positions', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podtip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, default='nophoto.jpg', upload_to='icon/')),
                ('map_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('short_body', models.TextField()),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumb_img', models.ImageField(blank=True, default='nophoto.jpg', upload_to='news/')),
                ('sort_positions', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='teslaways.zone')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='nophoto.jpg', upload_to='gallery-destination')),
                ('destinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationgallery', to='teslaways.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='pod_tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='teslaways.podtip'),
        ),
        migrations.AddField(
            model_name='destination',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teslaways.zone'),
        ),
    ]
