# Generated by Django 4.0.1 on 2022-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
