# Generated by Django 4.0.2 on 2022-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0003_alter_adminuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='repeat_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
