# Generated by Django 4.0.2 on 2022-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0004_adminuser_repeat_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='baneri')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
