# Generated by Django 4.0.2 on 2022-02-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0006_alter_banana_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destinacija', 'verbose_name_plural': 'Destinacije'},
        ),
        migrations.AlterModelOptions(
            name='destinationgallery',
            options={'verbose_name': 'Galerija za destinacije', 'verbose_name_plural': 'Galerija za destinacije'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Vest', 'verbose_name_plural': 'Vesti'},
        ),
        migrations.AlterModelOptions(
            name='podtip',
            options={'verbose_name': 'Podtip', 'verbose_name_plural': 'Podtipovi'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zone'},
        ),
    ]
