# Generated by Django 4.0.2 on 2022-02-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0007_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin i korisnici', 'verbose_name_plural': 'Admin i korisnici'},
        ),
    ]
