# Generated by Django 4.0.2 on 2022-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0008_alter_adminuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staticki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Staticka stranica',
                'verbose_name_plural': 'Staticke stranice',
            },
        ),
    ]
