# Generated by Django 4.0.2 on 2022-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0009_staticki'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticki',
            name='title',
            field=models.CharField(default='Neki naslov', max_length=255),
            preserve_default=False,
        ),
    ]
