# Generated by Django 4.0.2 on 2022-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0010_staticki_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slajder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='baneri')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slajder',
                'verbose_name_plural': 'Slajderi',
            },
        ),
    ]
