# Generated by Django 4.0.2 on 2022-02-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0011_slajder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='repeat_password',
        ),
    ]
