# Generated by Django 4.0.2 on 2022-02-17 12:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teslaways', '0013_alter_destination_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tip',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jesti', 'jesti'), ('spavati', 'spavati'), ('videti', 'videti')], max_length=20),
        ),
    ]
